//! freejoyx-ui
//!
//! Slint UI shell. Slice 5 ships the app window, tab strip skeleton
//! (all v0.1 tabs visible, only Pins implemented), and the Pins tab
//! body wired end-to-end to a [`freejoyx_device`] worker via the
//! channel API.
//!
//! Public entry: [`run`] — spawns the worker, builds the Slint window,
//! pumps the event channel into Slint model updates via
//! [`slint::Timer`], blocks on `slint::run_event_loop`. Returns when
//! the window closes.
//!
//! Slice 6+ will hang real tab bodies off [`AppWindow`]'s tab strip.

// Slint's generated `include_modules!` output uses `unsafe` for the
// item-tree vtable wiring; that's the framework boundary, not our
// code. Our hand-written sources stay `unsafe`-free — the `deny`
// (rather than `forbid`) lets the generated block opt out explicitly
// if it ever needs to without touching this attribute.
#![deny(unsafe_code)]
#![warn(clippy::pedantic)]
#![allow(clippy::similar_names)]
// pin-row variables are intentionally close
// Allowed pedantic lints in the WIP UI code -- these are not bugs, they're
// style/perf suggestions that don't fit how the Slint callbacks are shaped:
#![allow(clippy::cast_precision_loss)] // usize -> f32 for slot indices
#![allow(clippy::cast_sign_loss)] // i8/i32 -> usize for pin IDs
#![allow(clippy::cast_possible_truncation)] // narrowing widget-sized indices
#![allow(clippy::needless_range_loop)] // `for slot in 0..N` mirrors firmware loops
#![allow(clippy::trivially_copy_pass_by_ref)] // matches Slint callback signatures
#![allow(clippy::too_many_lines)] // UI builders are long by nature
#![allow(clippy::manual_let_else)] // legibility judgment call
#![allow(clippy::empty_line_after_doc_comments)] // stylistic; deferred

pub mod app;
pub mod debug_log;
pub mod log_dir;
mod settings;
mod tabs;

pub use app::run;

// Generated by build.rs from ui/app.slint. The macro re-imports
// `AppWindow` / `PinRow` as ordinary Rust types.
slint::include_modules!();
