//! freejoyx-ui
//!
//! Slint UI shell. Slice 5 ships the app window, tab strip skeleton
//! (all v0.1 tabs visible, only Pins implemented), and the Pins tab
//! body wired end-to-end to a [`freejoyx_device`] worker via the
//! channel API.
//!
//! Public entry: [`run`] — spawns the worker, builds the Slint window,
//! pumps the event channel into Slint model updates via
//! [`slint::Timer`], blocks on `slint::run_event_loop`. Returns when
//! the window closes.
//!
//! Slice 6+ will hang real tab bodies off [`AppWindow`]'s tab strip.

// Slint's generated `include_modules!` output uses `unsafe` for the
// item-tree vtable wiring; that's the framework boundary, not our
// code. Our hand-written sources stay `unsafe`-free — the `deny`
// (rather than `forbid`) lets the generated block opt out explicitly
// if it ever needs to without touching this attribute.
#![deny(unsafe_code)]
#![warn(clippy::pedantic)]
#![allow(clippy::similar_names)] // pin-row variables are intentionally close

mod advanced;
pub mod app;
mod buttons;
mod encoders;
pub mod log_dir;
mod settings;

pub use app::run;

// Generated by build.rs from ui/app.slint. The macro re-imports
// `AppWindow` / `PinRow` as ordinary Rust types.
slint::include_modules!();
